---
# To request membership in the CDISC Open Source Alliance (COSA), please email a YAML file with the following information to cosa@cdisc.org:
projectInfo:
  projectName: Schedule of Activities (SoA) Workbench
  projectOwner: Darren Moreland
  projectContact:
    - dmoreland@cdisc.org
  projectLandingPage: http://localhost:8000/
  projectRepository: https://github.com/pendingintent/soa-builder
  programmingLanguage: 
    - Python
  openSourceLicense:
    - MIT
  cdiscStandards:
    - USDM
  projectMaturity:
    - Development
  agreeWithCdiscCodeOfEthics: true
  user:
    - Protocol developers
    - Study developers
  logoUrl: images/CDISC-360i-Logo.png
detailedDescription:
  problem: >-
    An easy-to-use utility with user interface does not exist for the creation of a study schedule of activities. This 
    interface must allow the creation of an encounter matrix with the linking of CDISC Biomedical Concepts with the 
    activities to support the export of valid, standard-conformant USDM v4.0.
  solution: |- 
    A simple Python web-based application allows for the creation of SoA for multiple studies, which allows for editing of 
    a study SoA, version tracking, protocol amendments.  The solution supports associating biomedical concepts in the CDISC 
    library with activities defined in the SoA.  Diff reporting is supported for impact analysis. Multiple AI solutions are
    used in the implementation of this project.  copilot is also used in GitHub pull requests and code reviews.
  openSourceConsiderations: |- 
    This project is considered fully open-source and is available for cloning, branching, and forking.  This project is in 
    its early stages and, by making it open-source, the hope is other developers and volunteers will get involved to help 
    create a more robust solution that adds additional benefits to the industry.
  maintenanceModel: |- 
    The project is in development and available for branching, forking and contribution. Issues can be reported in GitHub.
    Issues are fixed via branching and raising Pull Requests which must be assigned to a Reviewer prior to Merge.
  projectSize: |-
    260MB currently with the expectation the project will grow as the project matures and features are added.
  contributors: |-
    Contributors must use the automated testing configured currently as well as those developed in future
    releases.
  userDetails: |-
    The primary users of SoA Workbench are clinical programmers, protocol developers, medical writers. 
  preRequisites: |- 
    Python and Git must be installed on a developer system.  Visual Studio Code is recommended as an IDE.
  projectServiceOptions: 
  sponsors: |- 
    CDISC Data Science
  goalsObjectives: |- 
    Creation of SoA for study and generation of USDM v4.0 JSON to be used in downstream processes for 360i project.
    Requirements:
      * UI to design a study with at least the study header info, info for trial design domains, and schedule of activities
      * Integration with CDISC Library for adding BCs to each activity in the SoA
      * Generate USDM-JSON 4.0
      * Amend a protocol and keep versioning 
      * Do an impact analysis (at minimum for this stage, just comparing difference between original protocol and amendment(s))
      * Simple SoA visualization (or at least csv/xlsx export) to review SoA.
      * Import existing protocols (can possibly use one of the open-source solutions from the AI Challenge; bonus add, not MVP)
  communications: n/a
  additonalInformation: |-
    https://github.com/pendingintent/soa-builder